name: LibraryManagement.API

on:
  push:
    paths:
      - "src/Services/LibraryManagement/**"
      - ".github/workflows/library-management.api.yml"
      - "src/Libraries/OpenTelemetry/**"
      - "build/dotnet/**"
      - "src/Directory.Build.props"
      - "docker-compose.yml"
      - "docker-compose.override.yml"
      - "docker-compose.dcproj"
      - "docker-compose-test.yml"
      - "docker-compose-test.override.yml"
  pull_request:
    paths:
      - "src/Services/LibraryManagement/**"
      - ".github/workflows/library-management.api.yml"
      - "src/Libraries/OpenTelemetry/**"
      - "build/dotnet/**"
      - "src/Directory.Build.props"
      - "docker-compose.yml"
      - "docker-compose.override.yml"
      - "docker-compose.dcproj"
      - "docker-compose-test.yml"
      - "docker-compose-test.override.yml"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set image tag
        run: echo "TAG=$(git tag --points-at HEAD | cut -c 2-4)" >> $GITHUB_ENV

      - name: build
        run: docker-compose build librarymanagement.api

      - uses: azure/docker-login@v1
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: push image
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
        run: docker-compose push librarymanagement.api

  StaticCodeAnalysis:
      name: CodeQL Analysis
      runs-on: ubuntu-latest
      needs: Build
       
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true
    
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v1
          with:
            languages: 'csharp'
    
        - name: Autobuild
          uses: github/codeql-action/autobuild@v1
    
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1
