name: LibraryManagement.API

on:
  push:
    paths:
      - "src/Services/LibraryManagement/**"
      - ".github/workflows/library-management.api.yml"
      - "src/Libraries/OpenTelemetry/**"
      - "build/dotnet/**"
      - "src/Directory.Build.props"
      - "docker-compose.yml"
      - "docker-compose.override.yml"
      - "docker-compose.dcproj"
      - "docker-compose-test.yml"
      - "docker-compose-test.override.yml"
  pull_request:
    paths:
      - "src/Services/LibraryManagement/**"
      - ".github/workflows/library-management.api.yml"
      - "src/Libraries/OpenTelemetry/**"
      - "build/dotnet/**"
      - "src/Directory.Build.props"
      - "docker-compose.yml"
      - "docker-compose.override.yml"
      - "docker-compose.dcproj"
      - "docker-compose-test.yml"
      - "docker-compose-test.override.yml"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set image tag
        run: echo "TAG=$(git tag --points-at HEAD | cut -c 2-4)" >> $GITHUB_ENV

      - name: build
        run: docker-compose build librarymanagement.api

      - uses: azure/docker-login@v1
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: push image
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
        run: docker-compose push librarymanagement.api

  StaticCodeAnalysis:
      name: CodeQL Analysis
      runs-on: ubuntu-latest
      needs: Build
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true
    
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v2
          with:
            languages: 'csharp'
    
        - name: Autobuild
          uses: github/codeql-action/autobuild@v2
    
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v2
          
  Sanitycheck:
      name: Sanity Check
      runs-on: ubuntu-latest
      needs: Build
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Install misspell
          run: |
            curl -L -o ./install-misspell.sh https://git.io/misspell
            sh ./install-misspell.sh
  
        - name: Run misspell
          run: ./bin/misspell -error .
          
  DockerPush:
    runs-on: ubuntu-latest
    needs: [Build, StaticCodeAnalysis, Sanitycheck]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set image tag
        run: |
          TAG=$(git tag --points-at HEAD)
          if [ -z "$TAG" ]; then
            TAG=$(git rev-parse --short HEAD)
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Print TAG value
        run: echo "TAG value is ${{ env.TAG }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Services/LibraryManagement/LibraryManagement.API/Dockerfile
          push: true
          tags: mohammadchalhoub/librarymanagement.api:${{ env.TAG }}

      - name: Run Docker container for testing
        run: |
          docker run -d --name test-container mohammadchalhoub/librarymanagement.api:${{ env.TAG }}
          docker ps -a
          docker logs test-container
